" pathogen
execute pathogen#infect()

""""""""""""""""""""""""""""""""""""""""""""
" 返回之前编辑所在位置
""""""""""""""""""""""""""""""""""""""""""""
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

autocmd! bufwritepost ~/.vimrc source ~/.vimrc



""""""""""""""""""""""""""""""""""""""""""""
" misc setting
""""""""""""""""""""""""""""""""""""""""""""
set t_Co=256
set autochdir
set lazyredraw
set backspace=eol,start,indent
set whichwrap+=<,>,h,l
set number
set so=7
syntax on
set autoread
set cursorline
set nocompatible
set autoindent
set smartindent
" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader = ","
let g:mapleader = ","




"""""""""""""""""""""""""""""""""""""""""""''
" tab managing
"""""""""""""""""""""""""""""""""""""""""""''
map <leader>tn :tabnew<cr>
map <leader>to :tabonly<cr>
map <leader>q :q<cr>
" <leader> te
map <leader>te :tabedit <c-r>=expand("%:p:h")<cr>/

nnoremap <C-N> :tabnext<CR>
nnoremap <C-P> :tabpre<CR>

map 0 ^


" Delete trailing white space on save, useful for some filetypes ;)
fun! CleanExtraSpaces()
    let save_cursor = getpos(".")
    let old_query = getreg('/')
    silent! %s/\s\+$//e
    call setpos('.', save_cursor)
    call setreg('/', old_query)
endfun

if has("autocmd")
    autocmd BufWritePre *.txt,*.js,*.py,*.wiki,*.sh,*.coffee :call CleanExtraSpaces()
endif

"set file encoding
set fileencoding=utf-8
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936


vnoremap <silent> * :<C-u>call VisualSelection('', '')<CR>/<C-R>=@/<CR><CR>
vnoremap <silent> # :<C-u>call VisualSelection('', '')<CR>?<C-R>=@/<CR><CR>



" tab设置
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

" 不使用历史文件
set nobackup

" set movement
nnoremap <C-j> jj
nnoremap <C-k> kk

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" 载入文件类型插件
filetype on
filetype plugin on
filetype indent on
syntax enable

" 显示匹配的括号
set showmatch
set mat=2

" 在左边添加一列
set foldcolumn=1


" 高亮搜索
set hlsearch



" Fast saving
nmap <leader>w :w<cr>

" :W sudo saves the file
" (useful for handling the permission-denied error)
command W w !sudo tee % > /dev/null

" Disable highlight when <leader><cr> is pressed
nmap <silent> <leader><cr> :noh<cr>
nmap <leader>p "+gp
vmap <leader>c "+y



" nerdcommenter
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1


nnoremap <F5> :!python %<cr>

""""""""""""""""""""""""""""""""""""""""""""
" UI setting
""""""""""""""""""""""""""""""""""""""""""""
set t_Co=256
set background=dark
colorscheme gruvbox

if has("gui_running")
    set guioptions-=e
    set guioptions-=m
    set guioptions-=T
    set guioptions-=r
    set guioptions-=L
    set guifont=Monospace\ 12
endif

