" pathogen
execute pathogen#infect()

" 返回之前编辑所在位置
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

autocmd! bufwritepost .vimrc source ~/.vimrc

" Color scheme

set t_Co=256
" let g:molokai_original=0

" colorscheme molokai
set background=dark
colorscheme gruvbox

if has("gui_running")
    set guioptions-=m
    set guioptions-=T
    set guioptions-=r
"    set guioptions=L
    set guifont=Droid\ Sans\ Mono\ 11
    colorscheme gruvbox
endif

" buffer switch
nnoremap <C-N> :bnext<CR>
nnoremap <C-P> :bprev<CR>

"set file encoding
set fileencoding=utf-8
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936


" Configure backspace so it acts as it should act
set backspace=eol,start,indent
set whichwrap+=<,>,h,l

" 显示行号
set number

" 语法高亮
syntax on

" 自动载入修改文件
set autoread

" 高亮当前行
set cursorline


set nocompatible

set autoindent
set smartindent

" tab设置
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

" 不使用历史文件
set nobackup

" set movement
nnoremap <C-j> jj
nnoremap <C-k> kk

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set laststatus=2
set cmdheight=1

" 载入文件类型插件
filetype on
filetype plugin on
filetype indent on
syntax enable

" 显示匹配的括号
set showmatch

" 在左边添加一列
set foldcolumn=1


" 高亮搜索
set hlsearch

" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader = ","
let g:mapleader = ","

" Fast saving
nmap <leader>w :w<cr>
nmap <leader>q :q<cr>

" :W sudo saves the file
" (useful for handling the permission-denied error)
" command W w !sudo tee % > /dev/null

" Disable highlight when <leader><cr> is pressed
nmap <silent> <leader><cr> :noh<cr>
nmap <leader>v "+gp
nmap <leader>c "+y



" youcompleteme
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g :YcmCompleter GoToDefinitionElseDeclaration<CR>


