#!/usr/bin/python3
# coding = utf-8

import urllib.request
import urllib.parse
import sys
import re


base_url = "http://159.226.39.22/cgi-bin/"


values = {
    "username": "dulei",
    "password": "dulei001",
}


uid = ''

headers ={
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0"
    }

def login():
    login_url = base_url + "do_login"

    data = urllib.parse.urlencode(values)
    data = data.encode('ascii')

    req = urllib.request.Request(login_url, data=data, headers=headers)

    try:
        response = urllib.request.urlopen(req)
        uid = response.read().decode('utf8')
    except urllib.error.HTTPError as e:
        print("The server could not handle the request.")
        print("Error code:%".format(e.code))
    
    pattern = re.compile(r'^[0-9]+$')
    if pattern.match(uid):
        print('Login Success!')
    elif uid == 'user_tab_error':
        print("认证程序未启动")
    elif uid == 'username_error':
        print("用户名错误")
    elif uid == 'non_auth_error':
        print("您无需认证,可直接上网")
    elif uid == 'password_error':
        print("密码错误")
    elif uid == 'status_error':
        print("用户已欠费,请充值")
    elif uid == 'available_error':
        print("用户已禁用")
    elif uid == 'ip_exist_error':
        print("您的ip未上线,请等待2分钟再试")
    elif uid == 'usernum_error':
        print("用户数已达上限")
    elif uid == 'online_num_error':
        print("该帐号的登录人数已超过限额\n如果怀疑帐号被盗用，请联系管理员。")
    elif uid == 'mode_error':
        print("系统已禁止WEB方式登录，请使用客户端")
    elif uid == 'time_policy_error':
        print("当前时段不允许连接")
    elif uid == 'flux_error':
        print("您的流量已超支")
    elif uid == 'minutes_error':
        print('您的时长已超支')
    elif uid == 'ip_error':
        print("您的ip不合法")
    elif uid == 'mac_error':
        print("mac不合法")
    elif uid == 'sync_error':
        print("您的资料已修改，正在等待同步，请2分钟后再试。")
    else:
        print("找不到服务器")


       

def logout():
    login_url = base_url + 'do_login'
    logout_url = base_url + "do_logout"

    data = urllib.parse.urlencode(values)
    data = data.encode('ascii')
    req = urllib.request.Request(login_url, data=data, headers=headers)
    uid = urllib.request.urlopen(req).read().decode('utf8')

    data1 = urllib.parse.urlencode({'uid':uid}).encode('ascii')
    req = urllib.request.Request(logout_url, data=data1, headers=headers)

    try:
        response = urllib.request.urlopen(req)
        info = response.read().decode('utf8')
    except urllib.error.HTTPError as e:
        print("Logout error.")
        print("Error code:%".format(e.code))
    if info == 'logout_ok':
        print("logout")
    elif info == 'logout_error':
        print('Not online!')
    else:
        print(info)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print('Need one argument!')
        sys.exit()
    else:
        if sys.argv[1] == '-i':
            login()
        elif sys.argv[1] == '-o':
            logout()
        else:
            print('Unknown argument!')
            sys.exit()
